apiVersion: v1
kind: Service
metadata:
  name: {{ include "rolling-update-chart.fullname" . }}
  labels:
    {{- include "rolling-update-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      {{ if eq .Values.service.type "NodePort"}}
      nodePort: {{ .Values.service.nodePort }}
      {{ end }}
      protocol: TCP
      name: http
  selector:
    {{- include "rolling-update-chart.selectorLabels" . | nindent 4 }}
